### ISSUE TITLE
syntax error in docker-compose.yaml file

### ISSUE THREAD

**Issue by ggascoigne** [MitchellJThomas/keycloak-react-app#1]
There should be a space between the `-` and `type` in https://github.com/MitchellJThomas/keycloak-react-app/blob/master/docker-compose.yaml#L31

should be 

```yaml
    volumes:
      - type: bind
        source: ./realm-export.json
        target: /tmp/realm-export.json
```
